/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StopsIndexRouteImport } from './routes/stops/index'
import { Route as TripIdRouteImport } from './routes/trip/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StopsIndexRoute = StopsIndexRouteImport.update({
  id: '/stops/',
  path: '/stops/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripIdRoute = TripIdRouteImport.update({
  id: '/trip/$id',
  path: '/trip/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trip/$id': typeof TripIdRoute
  '/stops/': typeof StopsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trip/$id': typeof TripIdRoute
  '/stops': typeof StopsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trip/$id': typeof TripIdRoute
  '/stops/': typeof StopsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/trip/$id' | '/stops/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/trip/$id' | '/stops'
  id: '__root__' | '/' | '/trip/$id' | '/stops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TripIdRoute: typeof TripIdRoute
  StopsIndexRoute: typeof StopsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stops/': {
      id: '/stops/'
      path: '/stops'
      fullPath: '/stops/'
      preLoaderRoute: typeof StopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$id': {
      id: '/trip/$id'
      path: '/trip/$id'
      fullPath: '/trip/$id'
      preLoaderRoute: typeof TripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TripIdRoute: TripIdRoute,
  StopsIndexRoute: StopsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
