/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripIdDateRouteImport } from './routes/trip/$id.$date'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripIdDateRoute = TripIdDateRouteImport.update({
  id: '/trip/$id/$date',
  path: '/trip/$id/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trip/$id/$date': typeof TripIdDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trip/$id/$date': typeof TripIdDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trip/$id/$date': typeof TripIdDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/trip/$id/$date'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/trip/$id/$date'
  id: '__root__' | '/' | '/trip/$id/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TripIdDateRoute: typeof TripIdDateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$id/$date': {
      id: '/trip/$id/$date'
      path: '/trip/$id/$date'
      fullPath: '/trip/$id/$date'
      preLoaderRoute: typeof TripIdDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TripIdDateRoute: TripIdDateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
